name: designsprit
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Cupertino
  cupertino_icons: ^1.0.5

  # Architecture
  dio: ^4.0.6
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.1
  get_it: ^7.2.0

  # Widgets
  syncfusion_flutter_calendar: ^20.4.42
  font_awesome_flutter: ^10.3.0
  cached_network_image: ^3.2.3
  introduction_screen: ^3.1.4
  fl_country_code_picker: ^0.1.2
  flutter_svg: ^2.0.0+1
  carousel_slider: ^4.2.1

  # Utils
  google_fonts: ^4.0.3
  url_launcher: ^6.1.8
  go_router: ^6.0.3
  easy_localization: ^3.0.1
  flutter_screenutil: ^5.6.1

  # Network
  sqflite: ^2.2.4+1
  shared_preferences: ^2.0.17
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  google_sign_in: ^5.4.4
  flutter_facebook_auth: ^5.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  change_app_package_name: ^1.1.0

flutter:

  uses-material-design: true

  assets:
  - assets/images/


  fonts:
    - family: GT Sectra Fine
      fonts:
        - asset: assets/fonts/GTSectraFineRegular.ttf