name: designsprit
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  dartz: ^0.10.1
  dio: ^4.0.6
  equatable: ^2.0.5
  flutter_bloc: ^8.1.1
  font_awesome_flutter: ^10.3.0
  get_it: ^7.2.0
  go_router: ^6.0.3
  google_fonts: ^4.0.3
  url_launcher: ^6.1.8
  introduction_screen: ^3.1.4
  country_code_picker: ^2.0.2
  cached_network_image: ^3.2.3

  email_validator: ^2.1.17

  cupertino_icons: ^1.0.5
  flutter_social_button: ^1.1.4+1
  flutter_svg: ^2.0.0+1
  modal_progress_hud_nsn: ^0.3.0
  shared_preferences: ^2.0.17
  intl_phone_field: ^3.1.0
  sqflite: ^2.2.4+1
  easy_localization: ^3.0.1

  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  google_sign_in: ^5.4.4
  flutter_facebook_auth: ^5.0.7
  carousel_slider: ^4.2.1

dependency_overrides:
  modal_bottom_sheet: ^3.0.0-pre

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  change_app_package_name: ^1.1.0

flutter:

  uses-material-design: true

  assets:
  - assets/images/


  fonts:
    - family: GT Sectra Fine
      fonts:
        - asset: assets/fonts/GTSectraFineRegular.ttf